version: "3.8"

services:

  pipeline:
    build: .
    container_name: cf_pipeline
    volumes:
      - .:/app
    command: python run_pipeline.py

  dashboard:
    build: .
    container_name: cf_dashboard
    ports:
      - "8501:8501"
    depends_on:
      - pipeline
    volumes:
      - .:/app
    command: streamlit run services/dashboard/app.py --server.address=0.0.0.0

  stream:
    build: .
    container_name: cf_stream
    depends_on:
      - pipeline
    volumes:
      - .:/app
    command: python services/stream/engine.py
